theme = "blackburn"
baseurl = "https://blog.kaznishi.com/"
title = "kaznishi I/O"
aurhor = "kaznishi"

copyright = "&copy; 2018-2021 kaznishi"
canonifyurls = true
paginate = 10

languageCode = "ja"
preserveTaxonomyNames = true
rssLimit = 10
pygmentsCodefences = true
pygmentsStyle = "native"
hasCJKLanguage = true

[taxonomies]
    category = "categories"  
    tag = "tags"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Categories"
    url = "/categories"
    weight = 10

[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 20

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 30

[params.meta]
    keywords = "技術ブログ, web"
    description = "個人的な備忘録ブログ"

[params]
    brand = "kaznishi I/O"
    googleTagManager = "GTM-5NS6LLS"
    subtitle = "個人的な備忘録ブログ"
    highlightjs = "dracula"

[social]
    twitter = "kaznishi1246"
    github = "kaznishi"
