baseurl = "https://blog.kaznishi.com/"
languageCode = "ja"
title = "kaznishi I/O"
theme = "hugo-natrium-theme"
preserveTaxonomyNames = true
rssLimit = 10
paginate = 10
pygmentsCodefences = true
pygmentsStyle = "native"
hasCJKLanguage = true
canonifyurls = true

[taxonomies]
    category = "categories"  
    tag = "tags"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = -110
    
[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = -120

[[menu.main]]
    name = "Categories"
    url = "/categories"
    weight = -130

[params.meta]
    keywords = "技術ブログ, web"
    description = "個人的な備忘録ブログ"

[params]
    googleTagManager = "GTM-5NS6LLS"

