baseURL = "https://kaznishi.netlify.com/"
languageCode = "ja"
hasCJKLanguage = true
title = "kaznishi I/O"

copyright = "Copyright (c) 2018, all rights reserved."
canonifyurls = true
paginate = 3
theme = "hugo-dusk"

googleAnalytics = ""
disqusShortname = ""

[author]
  name = "kaznishi"

SectionPagesMenu = "main"

# use Chroma for syntax highlight
pygmentsStyle = "vim" # other dark style options: vim, fruity, monokai
# enable syntax highlight for code blocks
pygmentsCodeFences = true

[[menu.main]]
  name = "Posts"
  weight = -120
  identifier = "post"
  url = "/post/"

[[menu.main]]
  name = "Tags"
  weight = -110
  identifier = "tag"
  url = "/tags/"

[[menu.main]]
  name = "About"
  weight = -100
  identifier = "about"
  url = "/about/"

[params.meta]
  keywords = "blog, tech"
  description = "個人的な備忘録ブログ"

[params]
  github = "kaznishi"
  gitlab = ""
  twitter = "kaznishi1246"
  linkedin = ""
  email = ""
  googleTagManager = "GTM-5NS6LLS"

[params.colors]
  # hugo-dusk colors
  background = "#101010" # background color for the site
  main = "#99cc66"
  text = "#dbdbdb"
  code-quote-bg = "#272822" # background color for quotes and code blocks
  copyright = "#404040" # copyright text color